steps:
- name: "gcr.io/cloud-builders/mvn"
  args:	
  - package
artifacts:
  objects:
    location: 'gs://resourcetechbucket/'
    paths:
    - "${_TARGET}"
artifacts:
  objects:
    location: 'gs://resourcetechbucket/start.sh'
