kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: startup-script
  labels:
    app: startup-script
spec:
  template:
    metadata:
      labels:
        app: startup-script
    spec:
      hostPID: true
      containers:
        - name: startup-script
          image: gcr.io/google-containers/startup-script:v1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
			steps:
        - name: "gcr.io/cloud-builders/mvn"
          args:	
        - package
artifacts:
  objects:
    location: 'gs://resourcetechbucket/'
    paths:
    - "${_TARGET}"
